// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT4o655xo-mf91QvDP0JmkGhpCrmVlhNA',
    appId: '1:897025027431:web:14e70fccb6bc7f5470d3c2',
    messagingSenderId: '897025027431',
    projectId: 'chatappok',
    authDomain: 'chatappok.firebaseapp.com',
    storageBucket: 'chatappok.appspot.com',
    measurementId: 'G-P5DWT0Z8RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6uR41IUoW0b8juAG6LdTdJBrbqEURlfI',
    appId: '1:897025027431:android:fefd7777ed5e4b3e70d3c2',
    messagingSenderId: '897025027431',
    projectId: 'chatappok',
    storageBucket: 'chatappok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHS1WqaRZeuVJyc5lLcHfsGYFqCH9yljY',
    appId: '1:897025027431:ios:d5435fe11f21427570d3c2',
    messagingSenderId: '897025027431',
    projectId: 'chatappok',
    storageBucket: 'chatappok.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHS1WqaRZeuVJyc5lLcHfsGYFqCH9yljY',
    appId: '1:897025027431:ios:4eb69ff4741027c170d3c2',
    messagingSenderId: '897025027431',
    projectId: 'chatappok',
    storageBucket: 'chatappok.appspot.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
